version: "3.3"

volumes:
  static_value:
  media_value:
  pg_data:

services:
  backend:
    build: ../backend/
    volumes:
      - ../backend/db.sqlite3:/var/lib/sqlite/data/db.sqlite3
      - static_value:/app/static/
      - media_value:/app/media/
    env_file: ../backend/.env
  # frontend:
  #   build: ../frontend/
  #   volumes:
  #     - ../frontend/:/app/result_build/
  #   depends_on:
  #     - backend
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/www/backend/static/
      - media_value:/var/www/backend/media/
    #   - ../frontend/dist:/usr/share/nginx/html/
    # depends_on:
    #   - frontend