# Generated by Django 3.2 on 2024-02-23 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=150)),
                ('breed', models.CharField(blank=True, max_length=150)),
                ('blood_type', models.CharField(blank=True, max_length=150)),
                ('age', models.IntegerField(blank=True)),
                ('habits', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, upload_to='avatar/')),
                ('nickname', models.CharField(blank=True, max_length=150)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
