# Generated by Django 4.2.10 on 2024-02-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_blood_types', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('city', models.CharField(max_length=150, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('reason', models.TextField(null=True)),
                ('progress', models.IntegerField(null=True)),
                ('blood_amount', models.IntegerField(null=True)),
                ('contact', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('breed', models.CharField(max_length=150, null=True)),
                ('blood_type', models.CharField(max_length=150, null=True)),
                ('age', models.IntegerField(null=True)),
                ('habits', models.TextField(null=True)),
                ('avatar', models.ImageField(null=True, upload_to='avatar/')),
                ('nickname', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=150, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('blood_amount', models.FloatField(null=True)),
                ('contact', models.CharField(max_length=150, null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
