name: Workflow

on:
  push:
    branches:
      - PROD

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python3

        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies for Python
        run: |
          pip install -r backend/requirements.txt

  build_and_push_to_docker_hub:
    name: Build and push docker image to docker hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push frontend to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend_selectel:latest

      - name: Push python backend file docker to docker hub
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend_selectel:latest

  deploy:
    name: Deploy image
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSPHRASE }}
          script: |
            cd site
            sudo docker-compose pull
            sudo docker-compose down
            sudo docker-compose up -d
            sudo docker exec site-backend-1 python manage.py makemigrations
            sudo docker exec site-backend-1 python manage.py migrate
            sudo docker exec site-backend-1 python -m nltk.downloader punkt
            sudo docker exec site-backend-1 python -m nltk.downloader wordnet

  send_message_telegram:
    name: message in tg
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: sms
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Деплой selectel успешно выполнен!
